export enum NavBarCyTags {
  NavbarMenuItems = 'menu',
  WalletConnectButton = 'button-connect-wallet',
  WalletLoginButton = 'button-login',
  WalletSignUpButton = 'button-signup'
}
export enum CommonCyTags {
  PercentageAmount = 'percentage-amount',
  MarketDropdown = 'market-dropdown',
  MarketPair = 'market-pair'
}

export enum MarketCyTags {
  MarketTicker = 'ticker',
  MarketBaseToken = 'base-token',
  HeaderLabel = 'header-label',
  MarketType = 'market-type',
  MarketSearch = 'market-search-field',
  MarketChain = 'market-chain',
  MarketQuoteToken = 'quote-token',
  MarketLastPrice = 'last-price',
  MarketPriceChange = 'price-change',
  MarketVolume = 'token-volume',
  MarketTrade = 'trade'
}

export enum SwapCyTags {
  SwapHeaderLabel = 'header-label',
  SwapForm = 'token-form',
  SwapSummaryRoute = 'summary-route',
  SwapSummaryRate = 'rate',
  SwapSummaryFees = 'fees',
  SwapSummaryMinOutput = 'min-output',
  SwapSummaryExpectedOutput = 'exp-output',
  BalanceString = 'balance-string',
  TokenEstUsdPrice = 'token-estimated-usd-price',
  WarningRateExpired = 'rate-expired',
  WarningInsufficientbalance = 'insufficient-balance-error',
  WarningAmountTooLow = 'amount-too-low-warning',
  EnterAmountButton = 'enter-amount-button',
  Swapbutton = 'swap-button',
  SlippageSelectorSetting = 'slippage-selector-setting'
}

export enum SpotMarketCyTags {
  SpotTradingMode = 'trading-mode',
  SpotTradingType = 'trading-type',
  SpotTradingSide = 'order-side',
  LimitPriceInputField = 'input-field-limit',
  LimitAmountInputField = 'input-field-limit-amount',
  TokenBuyBalance = 'token-buy-balance',
  TokenSellBalance = 'token-sell-balance',
  AdvancedSettings = 'advanced-settings',
  AdvancedSettingsPostOnly = 'advanced-settings-post-only',
  AdvancedSettingsBypassWarning = 'advanced-settings-bypass-price-warning',
  AdvancedSettingsSlippage = 'advanced-settings-slippage',
  DetailsTotal = 'details-total',
  DetailsAmount = 'details-amount',
  DetailsStableAmount = 'details-stable-amount',
  DetailsPrice = 'details-price',
  DetailsMakerFeeRate = 'details-maker-fee-rate',
  DetailsEstFeeRebate = 'details-est-fee-rebate',
  DetailsMakerTakerRate = 'details-maker-taker-rate',
  OrderDetailsDropDown = 'order-trade-details-dropdown',
  OrderDetailsDropdownOptions = 'dropdown-options',
  OpenOrdersRow = 'open-orders-history-row',
  OpenOrderMarketTicker = 'open-order-market-ticker',
  OpenOrderSide = 'open-order-side',
  OpenOrderPrice = 'open-order-price',
  OpenOrderQty = 'open-order-qty',
  OpenOrderUnfilledQty = 'open-order-unfilled-qty',
  OpenOrderFilledQty = 'open-order-filled-qty',
  OpenOrderTotalAmt = 'open-order-total-amt',
  OpenOrderTotalAmtTokenSymbol = 'open-order-total-amt-token-symbol',
  OrderHistoryTimestamp = 'order-history-timestamp',
  OrderHistoryMarketTicker = 'order-history-market-ticker',
  OrderHistoryType = 'order-history-type',
  OrderHistorySide = 'order-history-side',
  OrderHistoryPrice = 'order-history-price',
  OrderHistoryAmount = 'order-history-amount',
  OrderHistoryTotal = 'order-history-total',
  OrderHistoryTrigger = 'order-history-trigger',
  OrderHistoryStatus = 'order-history-status',
  CancelOrderButton = 'cancel-order-button',
  ExperimentalMarketLabel = 'experimental-market-label',
  IUnderstandButton = 'i-understand',
  DoNotShowAgainCheckbox = 'do-not-show-again',
  ChartHeader = 'chart-header',
  TradeStats = 'trade-stats',
  TradeStatsMarketSelector = 'market-selector',
  TradeStatsInfo = 'trade-stats-info',
  TradeStatsInfoPrice = 'trade-stats-info-price',
  TradeStatsInfoVol = 'trade-stats-info-vol',
  TradeStatsInfoHigh = 'trade-stats-info-high',
  TradeStatsInfoLow = 'trade-stats-info-low',
  OrderbookGrid = 'orderbook-grid',
  OrderDetails = 'order-details',
  OrderbookViewOptions = 'orderbook-view-options',
  OrderbookMidMarkPrice = 'orderbook-mid-mark-price',
  OrderbookGridBuys = 'orderbook-grid-buys',
  OrderbookGridSells = 'orderbook-grid-sells',
  OrderDetailsTable = 'order-details-table'
}

export enum PerpetualMarketCyTags {
  DerivativeTradeType = 'derivative-trade-type',
  TradeDirection = 'trade-direction',
  LimitpriceInputField = 'limit-price-input-field',
  LimitAmountInputField = 'limit-amount-input-field',
  AvailableBalance = 'available-balance',
  LeverageInputField = 'leverage-input-field',
  LeverageError = 'leverage-error',
  AdvancedSettings = 'advanced-settings',
  DetailsTotal = 'details-total',
  DetailsMargin = 'details-margin',
  DetailsTotalNotional = 'details-total-notional',
  DetailsQty = 'details-qty',
  DetailsAvgPrice = 'details-avg-price',
  DetailsEstLiquidationPrice = 'details-est-liquidation-price',
  DetailsMakerTakerRate = 'details-maker-taker-fee',
  DetailsFee = 'details-fee',
  OrderDetailsDropdown = 'order-details-dropdown',
  OrderDetailsDropdownOptions = 'dropdown-options',
  OpenPosMarketTicker = 'open-pos-market-ticker',
  OpenPosTradeDirection = 'open-pos-trade-direction',
  OpenPosAmount = 'open-pos-amount',
  OpenEntryPrice = 'open-pos-entry-price',
  OpenPosUnrealizedPnl = 'open-pos-unrealized-pnl',
  OpenPosTotalValue = 'open-pos-total-val',
  OpenPosMargin = 'open-pos-margin',
  OpenPosLiquidationPrice = 'open-pos-liquidation-price',
  OpenPosLeverage = 'open-pos-leverage',
  OpenPosClosePosition = 'open-pos-close-position-market',
  OpenPosClosePosLimit = 'open-pos-close-position-limit',
  OpenPosClosePositionQty = 'open-pos-close-positon-qty',
  OpenPosClosePosPrice = 'open-pos-close-positon-price',
  OrderHistoryTimeStamp = 'order-history-timestamp',
  OrderHistoryMarketTicker = 'order-history-market-ticker',
  OrderHistoryOrderType = 'order-history-order-type',
  OrderHistorySide = 'order-history-side',
  OrderHistoryPrice = 'order-history-price',
  OrderHistoryAmount = 'order-history-amount',
  OrderHistoryTotal = 'order-history-total',
  OrderHistoryOrderStatus = 'order-history-order-status',
  OpenOrdersMarketTicker = 'open-orders-market-ticker',
  OpenOrdersSide = 'open-orders-side',
  OpenOrdersPrice = 'open-orders-price',
  OpenOrdersAmount = 'open-orders-amount',
  OpenOrdersUnfilled = 'open-orders-unfilled',
  OpenOrdersFilled = 'open-orders-filled',
  OpenOrdersLeverageNa = 'open-orders-leverage-na',
  OpenOrdersLeverage = 'open-orders-leverage',
  OpenOrdersTotal = 'open-orders-total',
  TradeHistoryTimestamp = 'trade-history-timestamp',
  TradeHistoryMarketTicker = 'trade-history-market-ticker',
  TradeHistoryTradeType = 'trade-history-trade-type',
  TradeHistoryTradeSide = 'trade-history-trade-side',
  TradeHistoryPrice = 'trade-history-price',
  TradeHistoryAmount = 'trade-history-amount',
  TradeHistoryFee = 'trade-history-fee',
  TradeHistoryTotal = 'trade-history-total'
}

export enum PortfolioCyTags {
  PortfolioMenuItems = 'portfolio-menu',
  SubAccountDropdown = 'sub-account-dropdown',
  SubAccountDropdownOptions = 'sub-account-dropdown-options',
  SubAccountTotalBalance = 'total-balance',
  AssetSearch = 'asset-search',
  BalanceTokenSymbol = 'token-symbol',
  BalanceAvailableAmount = 'available-amount',
  BalanceInUseOrReservedAmount = 'use-reserved-amount',
  BalanceUnrealisedPnl = 'unrealised-pnl',
  BalanceTotalAmount = 'total-amount',
  BalanceTotalValue = 'total-value'
}
