name: Helix Staging Deployments

on:
  push:
    branches:
      - staging
      - master

jobs:
  staging-release:
    name: 'Deploy to staging'
    runs-on: ubuntu-22.04
    timeout-minutes: 30
    env:
      ## Public
      VITE_NAME: 'BETA - Helix: Decentralized Cryptocurrency Derivatives, Ethereum and Altcoin Exchange'
      VITE_PRODUCT: helix
      VITE_BASE_URL: https://staging.injective.exchange
      VITE_ENV: staging
      VITE_NETWORK: staging
      VITE_CHAIN_ID: injective-1
      VITE_ETHEREUM_CHAIN_ID: 1
      SOURCE_DIR: .output/public
      DEST_DIR: www

      ## Github Actions
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true

      ## Flags
      VPN_CHECKS_ENABLED: false
      VITE_MAINTENANCE_ENABLED: false
      VITE_IS_ONRAMPER_DEV_MODE: false

      ## Endpoints
      VITE_INDEXER_API_ENDPOINT: ''
      VITE_CHRONOS_API_ENDPOINT: ''
      VITE_EXPLORER_API_ENDPOINT: ''
      VITE_SENTRY_GRPC_ENDPOINT: ''
      VITE_SENTRY_REST_ENDPOINT: ''

      ## Geo location & VPN checks
      VITE_VPN_CHECKS_ENABLED: false
      VITE_GEO_IP_RESTRICTIONS_ENABLED: true
      VITE_GOOGLE_MAPS_KEY: ${{ secrets.VITE_GOOGLE_MAPS_KEY }}
      VITE_PROXY_DETECTION_API_KEY: ${{ secrets.VITE_PROXY_DETECTION_API_KEY }}

      ## Secret
      VITE_FEE_RECIPIENT: ${{ secrets.VITE_FEE_RECIPIENT }}
      VITE_FEE_PAYER_PUB_KEY: ${{ secrets.VITE_FEE_PAYER_PUB_KEY }}

      VITE_ALCHEMY_KEY: ${{ secrets.VITE_ALCHEMY_KEY }}
      VITE_BUGSNAG_KEY: ${{ secrets.VITE_BUGSNAG_KEY }}
      VITE_MIXPANEL_KEY: ${{ secrets.VITE_MIXPANEL_KEY }}
      VITE_MAGIC_APK_KEY: ${{ secrets.VITE_MAGIC_APK_KEY }}
      VITE_COINGECKO_API_KEY: ${{ secrets.VITE_COINGECKO_API_KEY }}
      VITE_SHEETDB_BEARER_TOKEN: ${{ secrets.VITE_SHEETDB_BEARER_TOKEN }}
      VITE_ONRAMPER_SIGNING_KEY: ${{ secrets.VITE_ONRAMPER_SIGNING_KEY }}
      VITE_ONRAMPER_API_KEY_DEV: ${{ secrets.VITE_ONRAMPER_API_KEY_DEV }}
      VITE_ONRAMPER_API_KEY_PROD: ${{ secrets.VITE_ONRAMPER_API_KEY_PROD }}
      VITE_WALLET_CONNECT_PROJECT_ID: ${{ secrets.VITE_WALLET_CONNECT_PROJECT_ID }}

      VITE_GOOGLE_ANALYTICS_KEY: ${{ secrets.VITE_GOOGLE_ANALYTICS_KEY }}
      VITE_GOOGLE_SITE_VERIFICATION_KEY: ${{ secrets.VITE_GOOGLE_SITE_VERIFICATION_KEY }}

      VITE_NEWSLETTER_API: ${{ secrets.VITE_NEWSLETTER_API }}
      VITE_NINJA_PASS_ENDPOINT: ${{ secrets.VITE_NINJA_PASS_ENDPOINT }}

      AWS_REGION: ${{ secrets.AWS_MAINNET_REGION }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_S3_BUCKET: ${{ secrets.AWS_S3_STAGING_BUCKET }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      CLOUDFRONT_DISTRIBUTION_ID: ${{ secrets.CLOUDFRONT_STAGING_DISTRIBUTION_ID }}

      NODE_OPTIONS: '--max_old_space_size=15360'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Using Node ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Setup libudev-dev
        run: |
          sudo apt-get update
          sudo apt-get install libudev-dev

      - name: Build app
        run: |
          yarn install --force
          yarn clean-up
          yarn generate

      - name: Use AWS CLI
        uses: chrislennon/action-aws-cli@v1.1

      - name: Sync to S3 bucket
        run: aws s3 sync dist/ s3://$AWS_S3_BUCKET/www --follow-symlinks --delete

      - name: Set Cache Headers
        run: aws s3 cp s3://$AWS_S3_BUCKET/www s3://$AWS_S3_BUCKET/www --exclude "*" --include "*.js" --include "*.css" --include "*.svg" --include "*.woff2" --include "*.woff" --include "*.ttf" --recursive --metadata-directive REPLACE --expires 2034-01-01T00:00:00Z --cache-control max-age=2592000,public

      - name: Invalidate Cloudfront CDN
        run: aws cloudfront create-invalidation --distribution-id=$CLOUDFRONT_DISTRIBUTION_ID --paths "/*"
