name: Helix Testnet Deployments

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - testnet

jobs:
  testnet-release:
    name: 'Deploy to testnet'
    runs-on: ubuntu-22.04
    timeout-minutes: 30
    env:
      ## Public
      VITE_NAME: 'TESTNET - Helix | Decentralized Derivatives Trading. Any Market. Anytime. Anywhere.'
      VITE_BASE_URL: https://testnet.helixapp.com
      VITE_ENV: testnet
      VITE_NETWORK: testnetSentry
      VITE_CHAIN_ID: injective-888
      VITE_ETHEREUM_CHAIN_ID: 11155111
      SOURCE_DIR: .output/public
      DEST_DIR: www

      ## Github Actions
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true

      ## Flags
      VITE_VPN_CHECKS_ENABLED: false
      VITE_MAINTENANCE_ENABLED: false
      VITE_GEO_IP_RESTRICTIONS_ENABLED: false

      ## Secret
      VITE_MERCURYO_KEY: ${{ secrets.VITE_MERCURYO_KEY }}
      VITE_FEE_RECIPIENT: ${{ secrets.VITE_FEE_RECIPIENT }}
      VITE_MAGIC_APK_KEY: ${{ secrets.VITE_MAGIC_APK_KEY }}
      VITE_NEWSLETTER_API: ${{ secrets.VITE_NEWSLETTER_API }}
      VITE_COINGECKO_API_KEY: ${{ secrets.VITE_COINGECKO_API_KEY }}
      VITE_MERCURYO_WIDGET_ID: ${{ secrets.VITE_MERCURYO_WIDGET_ID }}
      VITE_ALCHEMY_SEPOLIA_KEY: ${{ secrets.VITE_ALCHEMY_SEPOLIA_KEY }}
      VITE_NINJA_PASS_ENDPOINT: ${{ secrets.VITE_NINJA_PASS_ENDPOINT }}
      VITE_FEE_PAYER_PUB_KEY: ${{ secrets.VITE_TESTNET_FEE_PAYER_PUB_KEY }}

      AWS_REGION: ${{ secrets.AWS_TESTNET_REGION }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_S3_BUCKET: ${{ secrets.AWS_S3_TESTNET_BUCKET }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      CLOUDFRONT_DISTRIBUTION_ID: ${{ secrets.CLOUDFRONT_TESTNET_DISTRIBUTION_ID }}

      NODE_OPTIONS: '--max_old_space_size=15360'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Using Node ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Setup libudev-dev
        run: |
          sudo apt-get update
          sudo apt-get install libudev-dev

      - name: Build app
        run: |
          yarn install --force
          yarn clean-up
          yarn generate

      - name: Use AWS CLI
        uses: chrislennon/action-aws-cli@v1.1

      - name: Sync to S3 bucket
        run: aws s3 sync dist/ s3://$AWS_S3_BUCKET/www --follow-symlinks --delete

      - name: Set Cache Headers
        run: aws s3 cp s3://$AWS_S3_BUCKET/www s3://$AWS_S3_BUCKET/www --exclude "*" --include "*.js" --include "*.css" --include "*.svg" --include "*.woff2" --include "*.woff" --include "*.ttf" --recursive --metadata-directive REPLACE --expires 2034-01-01T00:00:00Z --cache-control max-age=2592000,public

      - name: Invalidate Cloudfront CDN
        run: aws cloudfront create-invalidation --distribution-id=$CLOUDFRONT_DISTRIBUTION_ID --paths "/*"
